import Link from "next/link";
import { ADMIN_ROLES, requireRole } from "@/lib/authz";

export const dynamic = "force-dynamic";

export default async function OpportunityRelaySetupPage() {
  await requireRole(ADMIN_ROLES);
  return <main className="mx-auto min-h-screen max-w-5xl px-6 py-12"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-widest text-brand-400">Mercury Call Desk</p><h1 className="mt-2 text-3xl font-semibold text-white">Opportunity result relay setup</h1><p className="mt-2 max-w-3xl text-gray-400">Use this reference to relay a verified GHL deal result back into the MiniCRM. This is a controlled state update only; it never creates a client account, commission, payment, or payout.</p></div><Link className="rounded-lg border border-ink-700 px-3 py-2 text-sm text-gray-200" href="/admin/integrations">Integration monitor</Link></div><section className="mt-8 rounded-2xl border border-ink-700 bg-ink-900 p-6"><h2 className="font-semibold text-white">GHL workflow action</h2><p className="mt-2 text-sm leading-6 text-gray-300">Trigger only when the opportunity outcome is finalized in your approved GHL pipeline. Send the request to <code className="text-brand-200">/api/ghl/opportunities</code> using the same approved GHL webhook authentication pattern used by Mercury Call Desk appointment relays.</p><div className="mt-5 overflow-x-auto rounded-xl border border-ink-700 bg-ink-950 p-4"><pre className="text-sm text-gray-200">{`{
  "ghl_event_id": "unique-opportunity-event-id",
  "location_id": "approved-ghl-location-id",
  "event_type": "OPPORTUNITY_WON",
  "ghl_opportunity_id": "ghl-opportunity-id",
  "ghl_contact_id": "ghl-contact-id",
  "mini_crm_lead_id": "optional-minicrm-lead-id"
}`}</pre></div><p className="mt-4 text-sm text-gray-400">Send <code className="text-brand-200">OPPORTUNITY_WON</code> or <code className="text-brand-200">OPPORTUNITY_LOST</code>. Keep the GHL event ID unique so retries stay idempotent. Include the MiniCRM Lead ID whenever it is available; otherwise the relay falls back to stored opportunity or contact matching.</p></section><section className="mt-6 grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-ink-700 bg-ink-900 p-5"><h2 className="font-semibold text-white">Expected routing</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-gray-300"><li>Opportunity Won moves a matched active Lead to Closed Won while keeping its owner unchanged.</li><li>Opportunity Lost moves an open matched Lead to Closed Lost.</li><li>A late Lost event cannot roll an already Closed Won Lead backward.</li><li>DNC and suppressed Leads retain audit evidence but are not changed.</li></ul></article><article className="rounded-2xl border border-ink-700 bg-ink-900 p-5"><h2 className="font-semibold text-white">Controlled test</h2><ol className="mt-3 space-y-2 text-sm leading-6 text-gray-300"><li>Send a Won event for a matched test Lead and confirm Closed Won plus audit history.</li><li>Send a Lost event for a separate open test Lead and confirm Closed Lost.</li><li>Send a later Lost event for the Closed Won test Lead and confirm the win is preserved.</li><li>Resend a prior event ID and confirm the relay creates no duplicate work.</li><li>Send an event for a suppressed test Lead and confirm no lifecycle change occurs.</li></ol><Link className="mt-5 inline-block rounded-lg border border-brand-500 px-3 py-2 text-sm text-brand-200" href="/admin/leads/testing">Open Lead acceptance test</Link></article></section><section className="mt-6 rounded-2xl border border-amber-800 bg-ink-900 p-5"><h2 className="font-semibold text-white">Safety boundary</h2><p className="mt-2 text-sm leading-6 text-gray-300">This relay records verified opportunity outcomes only. Client onboarding stays in the separate admin onboarding queue. Commission eligibility, payment collection, payouts, and Finance remain independently gated.</p></section></main>;
}
