import Link from "next/link";
import { ADMIN_ROLES, requireRole } from "@/lib/authz";
import { features } from "@/lib/features";

export const dynamic = "force-dynamic";

type Step = { title: string; detail: string; href?: string; action?: string };

const steps: Step[] = [
  { title: "1. Confirm controlled test setup", detail: "Use test agents and test records only. Keep the Lead module gated until the owner intentionally opens a controlled test window.", href: "/admin/operating-status", action: "Review gate state" },
  { title: "2. Preview controlled import samples", detail: "Use the controlled import templates. Preview must identify valid rows, invalid rows, duplicate-in-batch rows, and suppression matches before any commit.", href: "/admin/leads", action: "Open controlled import" },
  { title: "3. Commit approved test records", detail: "Committed rows must land in admin review only. Confirm they do not enter Open Pool automatically.", href: "/admin/leads", action: "Open review queue" },
  { title: "4. Validate review controls", detail: "Approve one test Lead to Cold or Hot, disqualify one with a reason, and suppress one with a compliance reason. Confirm audit history on each record.", href: "/admin/leads", action: "Review Leads" },
  { title: "5. Validate claim boundaries", detail: "A certified test agent may claim one eligible Open Pool Lead. A non-certified agent and a second agent must not be able to claim or act on that Lead.", href: "/portal/leads", action: "Open agent Leads" },
  { title: "6. Validate agent work", detail: "Create a note, set an outcome, schedule a callback, and confirm the callback appears in Tasks. Verify the Lead is visible only to its owner.", href: "/portal/tasks", action: "Open Tasks" },
  { title: "7. Validate contact-safety controls", detail: "Use a test Lead to submit DNC. Confirm scheduled callbacks cancel, the Lead is suppressed, and the record no longer appears in the agent workflow. Separately test Wrong Number or Out of Business.", href: "/portal/leads", action: "Open agent Leads" },
  { title: "8. Validate documented Open Pool returns", detail: "A previously assigned non-referral Lead with two-way contact may return to Open Pool only with a reason. Confirm a new import cannot be placed in Open Pool directly.", href: "/admin/leads/release", action: "Open return controls" },
  { title: "9. Validate GHL appointment attribution", detail: "For a matched test Lead, Booked/Confirmed/Rescheduled should retain ownership and set Demo Booked. Cancelled/No-show should create a same-owner follow-up.", href: "/admin/integrations", action: "Open Integration Monitor" },
  { title: "10. Record owner decision", detail: "Do not enable normal agent Lead access until every required test passes and exceptions have an approved remediation plan.", href: "/admin/audit", action: "Open audit history" },
];

export default async function LeadAcceptanceTestingPage() {
  await requireRole(ADMIN_ROLES);
  return <main className="mx-auto min-h-screen max-w-5xl px-6 py-12"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-widest text-brand-400">Mercury Call Desk</p><h1 className="mt-2 text-3xl font-semibold text-white">Lead MVP acceptance test</h1><p className="mt-2 max-w-3xl text-gray-400">A controlled, owner-approved test path for Leads. This page does not enable the module and it does not create test data automatically.</p></div><Link className="rounded-lg border border-ink-700 px-3 py-2 text-sm text-gray-200" href="/admin/readiness">Readiness board</Link></div><section className="mt-6 rounded-2xl border border-ink-700 bg-ink-900 p-5"><p className="text-sm text-gray-300">Lead feature gate: <span className={features.leads ? "font-semibold text-emerald-200" : "font-semibold text-amber-200"}>{features.leads ? "Controlled test enabled" : "Staged / locked"}</span></p><p className="mt-2 text-sm text-gray-400">Open the gate only for the short, supervised test window. Keep real lead imports and normal agent access paused until this checklist is complete.</p></section><section className="mt-8 space-y-3">{steps.map((step) => <article className="rounded-2xl border border-ink-700 bg-ink-900 p-5" key={step.title}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="font-semibold text-white">{step.title}</h2><p className="mt-2 text-sm leading-6 text-gray-300">{step.detail}</p></div>{step.href && <Link className="shrink-0 rounded-lg border border-brand-500 px-3 py-2 text-sm text-brand-200" href={step.href}>{step.action || "Open"}</Link>}</div></article>)}</section><section className="mt-8 rounded-2xl border border-emerald-900 bg-ink-900 p-6"><h2 className="font-semibold text-white">Exit criteria</h2><p className="mt-2 text-sm leading-6 text-gray-300">Approve normal Lead use only after the test confirms tenant isolation, review-first imports, Open Pool guardrails, agent ownership boundaries, DNC/suppression behavior, callback workflow, and GHL appointment attribution. Keep a written audit note for any exception or deferred item.</p></section></main>;
}
