import Link from "next/link";
import { ADMIN_ROLES, requireRole } from "@/lib/authz";
import { features } from "@/lib/features";

export const dynamic = "force-dynamic";

type Step = { title: string; detail: string; href?: string; action?: string };

const steps: Step[] = [
  { title: "1. Confirm controlled test setup", detail: "Use test Client Accounts and an approved test owner. Keep Commission and Finance disabled; this test validates service handling only.", href: "/admin/operating-status", action: "Review gate state" },
  { title: "2. Create a test Client Account", detail: "Use a Closed Won test Lead in the onboarding queue. Confirm one Client Account is created and retains the Lead, originating owner, and GHL identity context.", href: "/admin/servicing/onboarding", action: "Open onboarding" },
  { title: "3. Document launch", detail: "Complete the launch checklist. Confirm the account becomes Active when current on payments, or Payment Failed when a payment issue exists. No commission or payout should be created.", href: "/admin/servicing/launches", action: "Open launch confirmations" },
  { title: "4. Validate healthy-account protection", detail: "Keep a current-paying test Client Account quiet. Confirm that lack of routine activity alone does not create a case, reassign the account, or alter service ownership.", href: "/admin/servicing", action: "Open servicing workspace" },
  { title: "5. Validate triggered service work", detail: "Create documented work for a real trigger: client request, support issue, payment problem, renewal event, escalation, or documented review. Confirm a Service Case appears with the expected priority and due time.", href: "/admin/servicing/cases", action: "Open service cases" },
  { title: "6. Validate case resolution", detail: "Record the action and resolution. Confirm the case history remains available and the Client Account health reflects the documented result.", href: "/admin/servicing/cases", action: "Open case queue" },
  { title: "7. Validate reassignment / House handling", detail: "Use only a test account. Confirm a documented transfer preserves history and that the account moves to House only through an authorized servicing decision—not because a healthy account is quiet.", href: "/admin/servicing", action: "Open servicing workspace" },
  { title: "8. Confirm hard boundaries", detail: "Verify this workflow does not create a commission, approve a payout, collect a payment, store bank data, or invoke Finance execution.", href: "/admin/finance", action: "Open Finance readiness" },
  { title: "9. Record owner decision", detail: "Keep normal servicing access gated until every test passes or any exception has an owner-approved remediation plan.", href: "/admin/audit", action: "Open audit history" },
];

export default async function ServicingAcceptanceTestingPage() {
  await requireRole(ADMIN_ROLES);
  return <main className="mx-auto min-h-screen max-w-5xl px-6 py-12"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-widest text-brand-400">Mercury Call Desk</p><h1 className="mt-2 text-3xl font-semibold text-white">Client Servicing acceptance test</h1><p className="mt-2 max-w-3xl text-gray-400">A controlled test path for onboarding and ongoing client service. The process is triggered by meaningful account activity, not artificial quarterly check-ins on healthy paying clients.</p></div><Link className="rounded-lg border border-ink-700 px-3 py-2 text-sm text-gray-200" href="/admin/readiness">Readiness board</Link></div><section className="mt-6 rounded-2xl border border-ink-700 bg-ink-900 p-5"><p className="text-sm text-gray-300">Servicing feature gate: <span className={features.servicing ? "font-semibold text-emerald-200" : "font-semibold text-amber-200"}>{features.servicing ? "Controlled test enabled" : "Staged / locked"}</span></p><p className="mt-2 text-sm text-gray-400">This workflow must remain separate from commission eligibility and Finance execution. It measures documented service activity and outcomes—not silence on a healthy current-paying account.</p></section><section className="mt-8 space-y-3">{steps.map((step) => <article className="rounded-2xl border border-ink-700 bg-ink-900 p-5" key={step.title}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="font-semibold text-white">{step.title}</h2><p className="mt-2 text-sm leading-6 text-gray-300">{step.detail}</p></div>{step.href && <Link className="shrink-0 rounded-lg border border-brand-500 px-3 py-2 text-sm text-brand-200" href={step.href}>{step.action || "Open"}</Link>}</div></article>)}</section><section className="mt-8 rounded-2xl border border-emerald-900 bg-ink-900 p-6"><h2 className="font-semibold text-white">Exit criteria</h2><p className="mt-2 text-sm leading-6 text-gray-300">Proceed only after onboarding, launch, healthy-account protection, triggered case creation, resolution, documented reassignment, and financial-system boundaries all behave as expected. Record exceptions in the audit trail before normal servicing access is considered.</p></section></main>;
}
