import { readFileSync } from "node:fs";

function assertContains(path: string, expected: string) {
  const content = readFileSync(path, "utf8");
  if (!content.includes(expected)) {
    throw new Error(`${path} is missing required lead-flow guard: ${expected}`);
  }
}

assertContains("src/lib/claims.ts", "twoWayContactAt: { not: null }");
assertContains("src/lib/claims.ts", "openPoolReleaseAt: releaseAt");
assertContains("src/lib/claims.ts", "TWO_WAY_CONTACT_REQUIRED");
assertContains("src/lib/lead-workspace.ts", "logColdLeadCallInitiated");
assertContains("src/lib/lead-workspace.ts", "logColdLeadDisposition");
assertContains("src/lib/lead-workspace.ts", "ACTIVITY_ONLY_NO_SOFT_LOCK");
assertContains("src/lib/lead-workspace.ts", "reservesLead: false");
assertContains("src/app/portal/leads/page.tsx", "Cold Lead workspace");
assertContains("src/app/portal/leads/page.tsx", "selectedCold");
assertContains("src/app/portal/leads/page.tsx", "ColdLeadDialButton");
assertContains("src/components/cold-lead-dial-button.tsx", "Click to call logs activity first");
assertContains("src/components/cold-lead-dial-button.tsx", "/api/portal/leads/call-start");
assertContains("src/components/cold-lead-dial-button.tsx", "window.location.href = telHref(phone)");
assertContains("src/components/cold-lead-dial-button.tsx", "Dialer was not opened because activity must be logged first");
assertContains("src/app/api/portal/leads/call-start/route.ts", "logColdLeadCallInitiated");
assertContains("src/app/api/portal/leads/call-start/route.ts", "ACTIVITY_ONLY_NO_SOFT_LOCK");
assertContains("src/app/portal/workspace/page.tsx", "My Workspace");
assertContains("src/app/portal/workspace/page.tsx", "Work Cold Leads");
assertContains("src/app/portal/workspace/page.tsx", "Claim timer");
assertContains("src/app/admin/leads/testing/page.tsx", "Production Lead Flow acceptance");
assertContains("src/app/admin/leads/testing/page.tsx", "PRODUCTION_ACCEPTANCE_20260709");
assertContains("src/app/admin/leads/testing/page.tsx", "LEAD_PRODUCTION_ACCEPTANCE_RECORDED");
assertContains("src/app/admin/leads/testing/page.tsx", "STATUS_BASELINE_COMMIT");
assertContains("src/app/admin/leads/testing/page.tsx", "Deployment status baseline");
assertContains("src/app/admin/leads/testing/page.tsx", "current commit may be newer than this baseline");
assertContains("src/app/admin/leads/testing/page.tsx", "/admin/leads/acceptance-report");
assertContains("src/app/admin/leads/testing/page.tsx", "/api/admin/leads/acceptance-report.csv");
assertContains("src/app/admin/leads/testing/page.tsx", "revalidatePath(\"/admin/leads/acceptance-report\")");
assertContains("src/app/admin/readiness/page.tsx", "Production Lead Flow acceptance");
assertContains("src/app/admin/readiness/page.tsx", "LEAD_PRODUCTION_ACCEPTANCE_RECORDED");
assertContains("src/app/admin/readiness/page.tsx", "LeadProductionAcceptanceStep");
assertContains("src/app/admin/readiness/page.tsx", "totalSteps: 18");
assertContains("src/app/admin/readiness/page.tsx", "reportHref: \"/admin/leads/acceptance-report\"");
assertContains("src/app/admin/readiness/page.tsx", "exportHref: \"/api/admin/leads/acceptance-report.csv\"");
assertContains("src/app/admin/audit/page.tsx", "LEAD_PRODUCTION_ACCEPTANCE_RECORDED");
assertContains("src/app/admin/audit/page.tsx", "production Lead Flow acceptance");
assertContains("src/app/admin/audit/page.tsx", "AcceptanceOutcome");
assertContains("src/app/admin/audit/page.tsx", "readAcceptanceMetadata");
assertContains("src/app/admin/audit/page.tsx", "outcomeClass");
assertContains("src/app/admin/audit/page.tsx", "statusBaselineCommit");
assertContains("src/app/admin/audit/page.tsx", "Leads report");
assertContains("src/app/admin/audit/page.tsx", "Leads CSV");
assertContains("src/lib/lead-production-acceptance.ts", "LEAD_PRODUCTION_ACCEPTANCE_ACTION");
assertContains("src/lib/lead-production-acceptance.ts", "leadProductionAcceptanceGroups");
assertContains("src/app/api/admin/leads/acceptance-report/route.ts", "lead-production-acceptance");
assertContains("src/app/api/admin/leads/acceptance-report/route.ts", "readyForOwnerDecision");
assertContains("src/app/api/admin/leads/acceptance-report.csv/route.ts", "LEAD_PRODUCTION_ACCEPTANCE_EXPORT_CREATED");
assertContains("src/app/admin/leads/acceptance-report/page.tsx", "Lead Production Acceptance Report");
assertContains("src/app/admin/leads/acceptance-report/page.tsx", "Owner decision readiness");
assertContains("src/app/admin/leads/acceptance-report/page.tsx", "CSV export");
assertContains("src/app/admin/operating-status/page.tsx", "Production Lead Flow acceptance");
assertContains("src/app/admin/operating-status/page.tsx", "Custom-domain smoke passed");
assertContains("src/app/admin/operating-status/page.tsx", "review the Lead acceptance report");
assertContains("src/app/admin/operating-status/page.tsx", "Open report");
assertContains("src/app/admin/operating-status/page.tsx", "CSV export");
assertContains("src/app/admin/leads/testing/page.tsx", "Verify click-to-call logs activity first");
assertContains("src/app/admin/leads/testing/page.tsx", "Verify dialer blocks if logging fails");
assertContains("src/app/admin/leads/testing/page.tsx", "Verify no-answer and voicemail stay unowned");
assertContains("src/app/admin/leads/testing/page.tsx", "Verify My Workspace dashboard");
assertContains("src/app/admin/leads/testing/page.tsx", "Verify GHL opportunity hardening");
assertContains("src/app/admin/leads/replies/page.tsx", "Warm reply triage");
assertContains("src/app/admin/leads/replies/page.tsx", "openPoolReleaseAt: releaseAt");
assertContains("src/app/admin/leads/replies/page.tsx", "Warm-reply assignment requires a recorded two-way contact");
assertContains("src/app/admin/leads/replies/page.tsx", "starts the 45-day responsibility timer");
assertContains("src/lib/lead-appointment-attribution.ts", "GHL_APPOINTMENT_IGNORED");
assertContains("src/lib/lead-appointment-attribution.ts", "Suppressed Lead was not changed by a GHL appointment event");
assertContains("src/lib/lead-appointment-attribution.ts", "callbackExpedited");
assertContains("src/lib/lead-appointment-attribution.ts", "twoWayContactRecorded");
assertContains("src/app/api/ghl/appointments/route.ts", "leadIgnored");
assertContains("src/lib/lead-opportunity-attribution.ts", "GHL_OPPORTUNITY_IGNORED");
assertContains("src/lib/lead-opportunity-attribution.ts", "callbacksCancelled");
assertContains("src/lib/lead-opportunity-attribution.ts", "GHL_OPPORTUNITY_LOST_PRESERVED");
assertContains("src/app/api/ghl/opportunities/route.ts", "preservedClosedWon");
assertContains("src/app/api/ghl/opportunities/route.ts", "callbacksCancelled");
assertContains("src/lib/lead-aging-jobs.ts", "LEAD_AUTO_RETURNED_TO_OPEN_POOL");
assertContains("src/lib/lead-aging-jobs.ts", "LEAD_PROMOTED_TO_SHARK_TANK");
assertContains("src/app/api/cron/leads/aging/route.ts", "CRON_SECRET");
assertContains("src/app/api/cron/leads/aging/route.ts", "runLeadAgingSweep");

console.log("Lead flow alignment guard passed.");
