import { readFileSync } from "node:fs";

function assertContains(path: string, expected: string) {
  const content = readFileSync(path, "utf8");
  if (!content.includes(expected)) {
    throw new Error(`${path} is missing required lead-flow guard: ${expected}`);
  }
}

const guards: [string, string][] = [
  ["src/lib/claims.ts", "twoWayContactAt: { not: null }"],
  ["src/lib/claims.ts", "openPoolReleaseAt: releaseAt"],
  ["src/lib/claims.ts", "TWO_WAY_CONTACT_REQUIRED"],
  ["src/lib/lead-workspace.ts", "ACTIVITY_ONLY_NO_SOFT_LOCK"],
  ["src/lib/lead-workspace.ts", "reservesLead: false"],
  ["src/components/cold-lead-dial-button.tsx", "Click to call logs activity first"],
  ["src/components/cold-lead-dial-button.tsx", "Dialer was not opened because activity must be logged first"],
  ["src/app/api/portal/leads/call-start/route.ts", "ACTIVITY_ONLY_NO_SOFT_LOCK"],
  ["src/app/portal/leads/page.tsx", "Cold Lead workspace"],
  ["src/app/portal/leads/page.tsx", "Agent-friendly mode"],
  ["src/app/portal/leads/page.tsx", "Business rules are unchanged"],
  ["src/app/portal/workspace/page.tsx", "My Workspace"],
  ["src/app/portal/workspace/page.tsx", "Claim timer"],

  ["src/app/admin/command-center/page.tsx", "/admin/leads/acceptance-command-center"],
  ["src/app/admin/command-center/page.tsx", "Lead command center"],
  ["src/app/admin/command-center/page.tsx", "production acceptance entrypoints"],
  ["src/app/admin/leads/page.tsx", "/admin/leads/acceptance-command-center"],
  ["src/app/admin/leads/page.tsx", "Lead command center"],
  ["src/app/admin/leads/page.tsx", "Lead review"],
  ["src/lib/lead-production-acceptance.ts", "LEAD_PRODUCTION_ACCEPTANCE_ACTION"],
  ["src/lib/lead-production-acceptance.ts", "leadProductionAcceptanceGroups"],
  ["src/lib/lead-production-acceptance.ts", "leadProductionAcceptanceSteps"],
  ["src/lib/lead-production-acceptance.ts", "Verify click-to-call logs activity first"],
  ["src/lib/lead-production-acceptance.ts", "Verify no-answer and voicemail stay unowned"],
  ["src/lib/lead-production-acceptance.ts", "Use the controlled GHL event harness only"],
  ["src/app/admin/leads/testing/page.tsx", "Production Lead Flow acceptance"],
  ["src/app/admin/leads/testing/page.tsx", "/admin/leads/acceptance-command-center"],
  ["src/app/admin/leads/testing/page.tsx", "Command center"],
  ["src/app/admin/leads/testing/page.tsx", "revalidatePath(\"/admin/leads/acceptance-command-center\")"],
  ["src/app/admin/leads/testing/page.tsx", "revalidatePath(\"/admin/leads/acceptance-report\")"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "Lead Production Acceptance Report"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "/admin/leads/acceptance-command-center"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "Command center"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "Owner decision readiness"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "Controlled acceptance evidence"],
  ["src/app/api/admin/leads/acceptance-report/route.ts", "readyForOwnerDecision"],
  ["src/app/api/admin/leads/acceptance-report/route.ts", "controlledEvidence"],
  ["src/app/api/admin/leads/acceptance-report.csv/route.ts", "controlledEvidenceIncluded: true"],
  ["src/lib/acceptance-evidence-summary.ts", "getAcceptanceEvidenceSummary"],
  ["src/lib/acceptance-evidence-summary.ts", "liveGhlWorkflowActivated: false"],

  ["src/app/admin/leads/acceptance-command-center/page.tsx", "Lead acceptance command center"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "data-acceptance-command-center=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "Next safe action"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "Gates that remain closed"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "This command center is intentionally non-mutating"],
  ["src/app/admin/readiness/page.tsx", "commandHref: \"/admin/leads/acceptance-command-center\""],
  ["src/app/admin/readiness/page.tsx", "Lead command center"],
  ["src/app/admin/readiness/page.tsx", "Command center"],
  ["src/app/admin/operating-status/page.tsx", "Lead command center"],
  ["src/app/admin/operating-status/page.tsx", "Use the command center as the starting point"],
  ["src/app/admin/operating-status/page.tsx", "Command center"],

  ["src/app/admin/audit/page.tsx", "NextCRM-inspired timeline view"],
  ["src/app/admin/audit/page.tsx", "data-audit-ux=\"filter-bar\""],
  ["src/app/admin/audit/page.tsx", "Filtered audit timeline"],
  ["src/app/admin/audit/page.tsx", "metadataPreview"],
  ["src/app/admin/audit/page.tsx", "/admin/leads/acceptance-command-center"],
  ["src/app/admin/audit/page.tsx", "Lead command center"],
  ["src/app/admin/leads/controlled-test-data/page.tsx", "/admin/leads/acceptance-command-center"],
  ["src/app/admin/leads/controlled-test-data/page.tsx", "Command center"],
  ["src/app/admin/leads/controlled-test-data/page.tsx", "revalidatePath(\"/admin/leads/acceptance-command-center\")"],
  ["src/app/admin/integrations/test-events/page.tsx", "/admin/leads/acceptance-command-center"],
  ["src/app/admin/integrations/test-events/page.tsx", "Command center"],
  ["src/app/admin/integrations/test-events/page.tsx", "revalidatePath(\"/admin/leads/acceptance-command-center\")"],
  ["src/app/admin/integrations/page.tsx", "/admin/leads/acceptance-command-center"],
  ["src/app/admin/integrations/page.tsx", "Lead command center"],
  ["src/app/admin/integrations/page.tsx", "Open command center"],
  ["src/app/admin/leads/replies/page.tsx", "Warm reply triage"],
  ["src/app/admin/leads/replies/page.tsx", "starts the 45-day responsibility timer"],
  ["src/lib/lead-appointment-attribution.ts", "GHL_APPOINTMENT_IGNORED"],
  ["src/lib/lead-opportunity-attribution.ts", "GHL_OPPORTUNITY_LOST_PRESERVED"],
  ["src/lib/lead-aging-jobs.ts", "dryRun?: boolean"],
  ["src/lib/lead-aging-jobs.ts", "wouldReturnToOpenPool"],
  ["src/app/api/admin/leads/aging-preview/route.ts", "mutationPerformed: false"],
  ["src/app/api/cron/leads/aging/route.ts", "CRON_SECRET"],
  ["src/lib/controlled-test-leads.ts", "CONTROLLED_TEST_GHL_EXPORT_BLOCK"],
  ["src/app/admin/leads/controlled-test-data/page.tsx", "GHL export blocked by default"],
  ["src/app/api/admin/leads/controlled-test-data/route.ts", "ghlExportBlockedByDefault: true"],
  ["src/lib/controlled-ghl-test-events.ts", "The GHL test harness only accepts controlled test Leads"],
  ["src/lib/controlled-ghl-test-events.ts", "liveGhlWorkflowActivated: false"],
  ["src/app/admin/integrations/test-events/page.tsx", "Controlled GHL event harness"],
  ["src/app/api/admin/integrations/test-events/route.ts", "applyControlledGhlTestEvent"],

  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Lead acceptance runbook"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "data-acceptance-runbook=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Gates that remain closed"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Verify the two-way-contact claim gate"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Verify the Warm Reply Triage 45-day timer"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Verify DNC suppresses and cancels callbacks"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Only use the controlled GHL event harness"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "mutationPerformed:false"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "id={step.id}"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "Acceptance runbook"],

  ["src/app/admin/command-center/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/command-center/page.tsx", "Lead acceptance runbook"],
  ["src/app/admin/readiness/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/readiness/page.tsx", "Lead acceptance runbook"],
  ["src/app/admin/readiness/page.tsx", "Acceptance runbook"],
  ["src/app/admin/readiness/page.tsx", "runbookHref: \"/admin/leads/acceptance-runbook\""],

  ["src/app/admin/leads/testing/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/leads/testing/page.tsx", "Acceptance runbook"],

  ["src/app/admin/leads/acceptance-runbook/checklist/page.tsx", "Lead acceptance runbook — printable checklist"],
  ["src/app/admin/leads/acceptance-runbook/checklist/page.tsx", "data-acceptance-runbook-checklist=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-runbook/checklist/page.tsx", "Gates that remain closed"],
  ["src/app/admin/leads/acceptance-runbook/checklist/page.tsx", "Sign-off"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "/admin/leads/acceptance-runbook/checklist"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Printable checklist"],

  ["src/app/admin/operating-status/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/operating-status/page.tsx", "Lead acceptance runbook"],
  ["src/app/admin/audit/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/audit/page.tsx", "Lead acceptance runbook"],
  ["src/app/admin/leads/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/leads/page.tsx", "Lead acceptance runbook"],

  ["src/app/admin/leads/acceptance-report/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "Acceptance runbook"],
  ["src/app/admin/leads/controlled-test-data/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/leads/controlled-test-data/page.tsx", "Acceptance runbook"],
  ["src/app/admin/integrations/test-events/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/integrations/test-events/page.tsx", "Acceptance runbook"],
  ["src/app/admin/integrations/page.tsx", "/admin/leads/acceptance-runbook"],
  ["src/app/admin/integrations/page.tsx", "Lead acceptance runbook"],

  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Where to record each step"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "data-acceptance-runbook-matrix=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "LEAD_PRODUCTION_ACCEPTANCE_RECORDED"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Perform on"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Record on"],

  ["src/lib/acceptance-runbook-links.ts", "ACCEPTANCE_RUNBOOK_SECTION_BY_STEP"],
  ["src/lib/acceptance-runbook-links.ts", "\"click-to-call-logs-first\": \"click-to-call\""],
  ["src/lib/acceptance-runbook-links.ts", "acceptanceRunbookHref"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "How to test this step"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "/admin/leads/acceptance-history"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "Acceptance history"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "acceptanceRunbookHref(step.id)"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "Runbook"],
  ["src/app/admin/leads/testing/page.tsx", "Runbook step"],
  ["src/app/admin/leads/testing/page.tsx", "id={step.id}"],
  ["src/app/admin/leads/testing/page.tsx", "revalidatePath(\"/admin/leads/acceptance-history\")"],
  ["src/app/admin/leads/acceptance-history/page.tsx", "data-acceptance-history=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-history/page.tsx", "200 most recent immutable Lead production acceptance records"],
  ["src/app/admin/leads/acceptance-history/page.tsx", "/api/admin/leads/acceptance-history.csv"],
  ["src/app/admin/leads/acceptance-history/page.tsx", "acceptanceRunbookHref(stepId)"],
  ["src/app/api/admin/leads/acceptance-history.csv/route.ts", "LEAD_PRODUCTION_ACCEPTANCE_HISTORY_EXPORT_CREATED"],
  ["src/app/api/admin/leads/acceptance-history.csv/route.ts", "sourceLimit: 200"],
  ["src/app/api/admin/leads/acceptance-history.csv/route.ts", "acceptanceRunbookHref(stepId)"],

  ["src/lib/lead-acceptance-findings.ts", "LEAD_ACCEPTANCE_FINDINGS_CATALOG_VERSION"],
  ["src/lib/lead-acceptance-findings.ts", "eighteen-steps-eleven-sections"],
  ["src/lib/lead-acceptance-findings.ts", "owner-acceptance-remains-hamilton-only"],
  ["src/app/admin/leads/acceptance-findings/page.tsx", "data-acceptance-findings=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-findings/page.tsx", "Lead acceptance findings catalog"],
  ["src/app/admin/leads/acceptance-findings/page.tsx", "Findings session"],
  ["src/app/api/admin/leads/acceptance-findings/route.ts", "leadAcceptanceFindings"],
  ["src/app/api/admin/leads/acceptance-findings/route.ts", "Read-only findings catalog only"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "/admin/leads/acceptance-findings"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "Findings catalog"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "/admin/leads/acceptance-findings"],
  ["src/app/admin/leads/acceptance-history/page.tsx", "/admin/leads/acceptance-findings"],

  ["src/lib/lead-acceptance-handoff.ts", "LEAD_ACCEPTANCE_HANDOFF_PACKET_VERSION"],
  ["src/lib/lead-acceptance-handoff.ts", "getLeadAcceptanceHandoffPacket"],
  ["src/lib/lead-acceptance-handoff.ts", "leadAcceptanceClosedGates"],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "data-acceptance-handoff=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "Lead acceptance handoff packet"],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "Handoff recommendation"],
  ["src/app/api/admin/leads/acceptance-handoff/route.ts", "getLeadAcceptanceHandoffPacket"],
  ["src/app/api/admin/leads/acceptance-handoff/route.ts", "Read-only acceptance handoff packet only"],
  ["src/app/admin/leads/acceptance-findings/page.tsx", "/admin/leads/acceptance-handoff"],

  ["src/lib/lead-acceptance-gaps.ts", "LEAD_ACCEPTANCE_GAPS_VERSION"],
  ["src/lib/lead-acceptance-gaps.ts", "getLeadAcceptanceEvidenceGaps"],
  ["src/lib/lead-acceptance-gaps.ts", "recordHref"],
  ["src/app/admin/leads/acceptance-gaps/page.tsx", "data-acceptance-gaps=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-gaps/page.tsx", "Lead acceptance evidence gaps"],
  ["src/app/admin/leads/acceptance-gaps/page.tsx", "Next evidence gap"],
  ["src/app/api/admin/leads/acceptance-gaps/route.ts", "getLeadAcceptanceEvidenceGaps"],
  ["src/app/api/admin/leads/acceptance-gaps/route.ts", "Read-only acceptance evidence gaps only"],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "/admin/leads/acceptance-gaps"],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "View evidence gaps"],

  ["src/lib/lead-acceptance-matrix.ts", "LEAD_ACCEPTANCE_MATRIX_VERSION"],
  ["src/lib/lead-acceptance-matrix.ts", "getLeadAcceptanceEvidenceMatrix"],
  ["src/lib/lead-acceptance-matrix.ts", "recordHref"],
  ["src/app/admin/leads/acceptance-matrix/page.tsx", "data-acceptance-matrix=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-matrix/page.tsx", "Lead acceptance evidence matrix"],
  ["src/app/admin/leads/acceptance-matrix/page.tsx", "All acceptance evidence rows"],
  ["src/app/api/admin/leads/acceptance-matrix/route.ts", "getLeadAcceptanceEvidenceMatrix"],
  ["src/app/api/admin/leads/acceptance-matrix/route.ts", "Read-only acceptance evidence matrix only"],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "/admin/leads/acceptance-matrix"],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "View evidence matrix"],
  ["src/app/admin/leads/acceptance-gaps/page.tsx", "/admin/leads/acceptance-matrix"],

  ["src/lib/lead-acceptance-gates.ts", "LEAD_ACCEPTANCE_GATES_VERSION"],
  ["src/lib/lead-acceptance-gates.ts", "getLeadAcceptanceClosedGates"],
  ["src/lib/lead-acceptance-gates.ts", "leadAcceptanceClosedGates"],
  ["src/app/admin/leads/acceptance-gates/page.tsx", "data-acceptance-gates=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-gates/page.tsx", "Lead acceptance closed gates"],
  ["src/app/admin/leads/acceptance-gates/page.tsx", "Closed-gates recommendation"],
  ["src/app/api/admin/leads/acceptance-gates/route.ts", "getLeadAcceptanceClosedGates"],
  ["src/app/api/admin/leads/acceptance-gates/route.ts", "Read-only closed acceptance gates only"],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "/admin/leads/acceptance-gates"],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "View closed gates"],
  ["src/app/admin/leads/acceptance-gaps/page.tsx", "/admin/leads/acceptance-gates"],
  ["src/app/admin/leads/acceptance-matrix/page.tsx", "/admin/leads/acceptance-gates"],

  ["src/lib/lead-acceptance-overview.ts", "LEAD_ACCEPTANCE_OVERVIEW_VERSION"],
  ["src/lib/lead-acceptance-overview.ts", "getLeadAcceptanceOverview"],
  ["src/lib/lead-acceptance-overview.ts", "leadAcceptanceOverviewEntries"],
  ["src/app/admin/leads/acceptance-overview/page.tsx", "data-acceptance-overview=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-overview/page.tsx", "Lead acceptance overview"],
  ["src/app/admin/leads/acceptance-overview/page.tsx", "Overview recommendation"],
  ["src/app/api/admin/leads/acceptance-overview/route.ts", "getLeadAcceptanceOverview"],
  ["src/app/api/admin/leads/acceptance-overview/route.ts", "Read-only Lead acceptance overview only"],
  ["src/app/admin/leads/acceptance-handoff/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/acceptance-gaps/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/acceptance-matrix/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/acceptance-gates/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/acceptance-history/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/acceptance-findings/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/acceptance-command-center/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/acceptance-report/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/testing/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/acceptance/page.tsx", "requireRole(ADMIN_ROLES)"],
  ["src/app/admin/leads/acceptance/page.tsx", "redirect(\"/admin/leads/acceptance-overview\")"],
  ["src/app/admin/leads/page.tsx", "/admin/leads/acceptance-overview"],
  ["src/app/admin/leads/page.tsx", "Lead acceptance overview"],

  ["src/lib/lead-workspace.ts", "ADMIN_ROLES"],
  ["src/lib/lead-workspace.ts", "isControlledTestLead"],
  ["src/lib/lead-workspace.ts", "Admins may only act on controlled test Leads"],
  ["src/lib/lead-workspace.ts", "Auto-provisioned acceptance operator"],
  ["src/app/portal/leads/page.tsx", "id=\"cold-lead-review\""],
  ["src/app/portal/leads/page.tsx", "#cold-lead-review"],

  ["src/lib/claims.ts", "isControlledTestLead"],
  ["src/lib/claims.ts", "Admins may only claim controlled test Leads"],
  ["src/lib/claims.ts", "acceptance-operator path"],

  ["src/lib/lead-acceptance-deferred.ts", "LEAD_ACCEPTANCE_DEFERRED_VERSION"],
  ["src/lib/lead-acceptance-deferred.ts", "DEFERRED_ACCEPTANCE_STEP_IDS"],
  ["src/lib/lead-acceptance-deferred.ts", "runtime-error-log-check"],
  ["src/lib/lead-acceptance-deferred.ts", "click-to-call-blocks-on-error"],
  ["src/lib/lead-acceptance-deferred.ts", "warm-reply-timer"],
  ["src/lib/lead-acceptance-deferred.ts", "ghl-appointment-hardening"],
  ["src/lib/lead-acceptance-deferred.ts", "ghl-opportunity-hardening"],
  ["src/lib/lead-acceptance-deferred.ts", "getLeadAcceptanceDeferredRunbook"],
  ["src/app/admin/leads/acceptance-runbook/deferred/page.tsx", "data-acceptance-deferred-runbook=\"lead-flow\""],
  ["src/app/admin/leads/acceptance-runbook/deferred/page.tsx", "Deferred acceptance runbook"],
  ["src/app/admin/leads/acceptance-runbook/deferred/page.tsx", "Where to record"],
  ["src/app/admin/leads/acceptance-runbook/deferred/page.tsx", "Acceptance board"],
  ["src/app/admin/leads/acceptance-runbook/deferred/page.tsx", "Read-only view of the five deferred production-acceptance steps"],
  ["src/app/admin/leads/acceptance-runbook/deferred/page.tsx", "data-deferred-acceptance-step={step.id}"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "/admin/leads/acceptance-runbook/deferred"],
  ["src/app/admin/leads/acceptance-runbook/page.tsx", "Deferred steps"],
  ["src/app/admin/leads/testing/page.tsx", "/admin/leads/acceptance-runbook/deferred"],
  ["src/app/admin/leads/testing/page.tsx", "data-acceptance-board-step-id={step.id}"],
  ["src/app/admin/leads/testing/page.tsx", "scroll-mt-6"],
  ["src/lib/lead-acceptance-overview.ts", "deferred-steps"],
  ["src/lib/lead-acceptance-overview.ts", "/admin/leads/acceptance-runbook/deferred"],
];

for (const [path, expected] of guards) {
  assertContains(path, expected);
}

console.log("Lead flow alignment guard passed.");
