import Link from "next/link";
import { ADMIN_ROLES, requireRole } from "@/lib/authz";
import { features } from "@/lib/features";

export const dynamic = "force-dynamic";

type Step = { title: string; detail: string; href?: string; action?: string };

const steps: Step[] = [
  { title: "1. Confirm schema approval", detail: "Validate the isolated commission migration on the approved Neon safety branch before considering a production migration. Do not insert production-like data during this check.", href: "/admin/operating-status", action: "Review operating status" },
  { title: "2. Confirm Commission gate and Finance separation", detail: "Open Commission only for a supervised test window. Keep Finance disabled. The Commission workspace must not initiate a transfer, collect a payment, or expose bank details.", href: "/admin/commissions", action: "Open commissions" },
  { title: "3. Validate active agent eligibility", detail: "Use a test Client Account with an active servicing owner. Confirm eligibility requires the documented owner, an eligible profile, payment clearance, and no active hold.", href: "/admin/commissions", action: "Open eligibility review" },
  { title: "4. Validate retirement and termination policy", detail: "Confirm a retired test agent retains existing-client eligibility when policy conditions are met. Confirm a terminated agent cannot receive future eligibility entries.", href: "/admin/commissions", action: "Open agent profiles" },
  { title: "5. Validate holds", detail: "Create a controlled hold scenario for an uncleared payment, refund, chargeback, or manual review. Confirm the ledger item stays on hold and cannot advance through review.", href: "/admin/commissions", action: "Open ledger review" },
  { title: "6. Validate clearance path", detail: "After documented payment clearance and hold removal, confirm the entry can be reviewed as eligible. A review result is not a payout authorization.", href: "/admin/commissions", action: "Open eligibility review" },
  { title: "7. Validate audit history", detail: "Confirm profile changes, eligibility reviews, hold activity, and clearance evidence appear in the audit trail with the responsible admin and reason.", href: "/admin/audit", action: "Open audit history" },
  { title: "8. Confirm no-money-movement boundary", detail: "Verify that no Commission test creates a payment-provider action, payment instruction, payout release, or Finance approval. Those remain separately gated.", href: "/admin/finance", action: "Open Finance readiness" },
];

export default async function CommissionAcceptanceTestingPage() {
  await requireRole(ADMIN_ROLES);
  return <main className="mx-auto min-h-screen max-w-5xl px-6 py-12"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-widest text-brand-400">Mercury Call Desk</p><h1 className="mt-2 text-3xl font-semibold text-white">Commission acceptance test</h1><p className="mt-2 max-w-3xl text-gray-400">A controlled eligibility-and-ledger test path. This phase evaluates policy and evidence only; it never authorizes or executes a payout.</p></div><Link className="rounded-lg border border-ink-700 px-3 py-2 text-sm text-gray-200" href="/admin/readiness">Readiness board</Link></div><section className="mt-6 rounded-2xl border border-ink-700 bg-ink-900 p-5"><p className="text-sm text-gray-300">Commission feature gate: <span className={features.commissions ? "font-semibold text-emerald-200" : "font-semibold text-amber-200"}>{features.commissions ? "Controlled test enabled" : "Staged / locked"}</span></p><p className="mt-2 text-sm text-gray-400">Finance remains separate. No account number, routing number, payment credential, or transfer instruction belongs in this test.</p></section><section className="mt-8 space-y-3">{steps.map((step) => <article className="rounded-2xl border border-ink-700 bg-ink-900 p-5" key={step.title}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="font-semibold text-white">{step.title}</h2><p className="mt-2 text-sm leading-6 text-gray-300">{step.detail}</p></div>{step.href && <Link className="shrink-0 rounded-lg border border-brand-500 px-3 py-2 text-sm text-brand-200" href={step.href}>{step.action || "Open"}</Link>}</div></article>)}</section><section className="mt-8 rounded-2xl border border-emerald-900 bg-ink-900 p-6"><h2 className="font-semibold text-white">Exit criteria</h2><p className="mt-2 text-sm leading-6 text-gray-300">Proceed only after the schema decision, eligibility policy, retirement and termination rules, payment clearance, holds, and audit evidence have all passed. An eligible ledger item remains review-only until the separately gated Finance phase is approved.</p></section></main>;
}
